language: ruby
rvm: # See .ruby-version for ruby version to use through RVM

sudo: false
before_install:
  # Install node manually because Travis only supports one language definition
  - . $HOME/.nvm/nvm.sh # Enable nvm
  - nvm install # This should pick up the version from .nvmrc
  - nvm use # Select the .nvmrc version for use

  # 29/12/2016: Only run Rails tests for now
  # # Yarn installation, can be run with sudo: false above
  # - curl -o- -L https://yarnpkg.com/install.sh | bash
  # - export PATH=$HOME/.yarn/bin:$PATH

install:
  - cd server/
  - gem install bundler
  - bundle install --deployment --without development production
  - cd ../

  # 29/12/2016: Only run Rails tests for now
  #- cd client/
  #- yarn install
  #- cd ../

script:
  - cd server/
  # Manually run db:migrate on the base database due to the older SQLite version used by Travis not supporting multi-INSERT statements as triggered during a migration
  # See here: https://github.com/rails/rails/issues/26948
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
  - cd ../

  # 29/12/2016: Only run Rails tests for now
  #- cd client/
  #- yarn test
  #- cd ../

cache:
  -bundler: true
  -yarn: true
  directories:
    - server/vendor/bundle
    - client/node_modules
