language: ruby
rvm: # See .ruby-version for ruby version to use through RVM

sudo: false
before_install:
  # Install node manually because Travis only supports one language definition
  - . $HOME/.nvm/nvm.sh # Enable nvm
  - nvm install # This should pick up the version from .nvmrc
  - nvm use # Select the .nvmrc version for use

  # 29/12/2016: Only run Rails tests for now
  # # Yarn installation, can be run with sudo: false above
  # - curl -o- -L https://yarnpkg.com/install.sh | bash
  # - export PATH=$HOME/.yarn/bin:$PATH

install:
  - pwd
  - cd server/ && gem install bundler && bundle install --deployment --without development production
  # 29/12/2016: Only run Rails tests for now
  #- cd ../client/ && yarn install
script:
  - cd server/ && bundle exec rspec spec
  # 29/12/2016: Only run Rails tests for now
  #- cd ../client/ && yarn test

cache:
  -bundler: true
  -yarn: true
  directories:
    - server/vendor/bundle
    - client/node_modules
