# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Default to using a secret key from the environment for travis builds
# Remove this for standard development and fill in the commented values below
test:
  secret_key_base: <%= ENV["TEST_SECRET_KEY_BASE"] %>

# NOTE: Once these details are set, you will need to run the following Git
#       command to prevent edits to secrets.yml from being tracked:
#
#       git update-index --assume-unchanged server/config/secrets.yml
#
# development:
#   secret_key_base: PUT_A_SECRET_KEY_HERE
#
# test:
#   secret_key_base: PUT_ANOTHER_SECRET_KEY_HERE

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
